name: snake animation

on:
  schedule:
    - cron: "0 0 * * 6" 
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/sanke/github-contribution-grid-snake.svg
            assets/sanke/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update snake animation 
